baseURL = "https://jojo.dev/"
languageCode = "en-us"
title = "systematica"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
defaultTheme = "dark"
disableThemeToggle = false
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowWordCount = true
ShowLastMod = true
defaultContentType = "posts"
[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/Mojojojomomo"

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/Mojojojomomo_hermes_bot"

[menu]
[[menu.main]]
identifier = "home"
name = "⌂ home"
url = "/"
weight = 1

[[menu.main]]
identifier = "archives"
name = "⟁ archives"
url = "/archives"
weight = 10

[[menu.main]]
identifier = "search"
name = "⌕ search"
url = "/search"
weight = 20

[[menu.main]]
identifier = "categories"
name = "◉ categories"
url = "/categories"
weight = 30

[[menu.main]]
identifier = "tags"
name = "⌗ tags"
url = "/tags"
weight = 40

[outputs]
home = [ "HTML", "RSS", "JSON",]

[params.assets]
disableFingerprinting = false

[params.editURL]
enable = false

[params.profileMode]
enabled = true
title = "systematica"
subtitle = "random hacks · systems thinking · code & chaos"
imageUrl = "/img/avatar.png"
imageTitle = "systematica"
imageWidth = 120
imageHeight = 120
[[params.profileMode.buttons]]
name = "Archives"
url = "/archives"

[[params.profileMode.buttons]]
name = "Search"
url = "/search"

[params.homeInfoParams]
Title = "systematica"
Content = "**random hacks · systems thinking · code & chaos**\n\nNo ads. No tracking. Minimalist dark-mode blog for technical scribbles.\n"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 3

[params.label]
text = "systematica"
icon = "/img/avatar.png"

[params.customCSS]
enable = true
files = [ "css/custom.css",]

[services.googleAnalytics]
ID = ""

[markup.highlight]
style = "paraiso-dark"
lineNos = true
lineNumbersInTable = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
linkify = true
